In [4]:
import numpy as np

a = np.array([1, 2, 3])  # Tạo mảng 1 chiều
print(type(a), a.shape, a[0], a[1], a[2])  # Kiểm tra kiểu và truy cập phần tử
a[0] = 5  # Thay đổi giá trị phần tử
print(a)  # Xuất mảng sau khi thay đổi

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [5]:
import numpy as np

# Tạo mảng 2D có kích thước (3,4)
a = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8], 
              [9, 10, 11, 12]])

# Trích xuất một sub-array gồm 2 hàng đầu tiên và cột 1, 2
b = a[:2, 1:3]  

print(b)

[[2 3]
 [6 7]]


In [6]:
import numpy as np

# Để NumPy tự động chọn kiểu dữ liệu
x = np.array([1, 2])      

# Mảng có số thực, NumPy sẽ chọn float64
y = np.array([1.0, 2.0])  

# Ép kiểu thành int64
z = np.array([1, 2], dtype=np.int64)  

# In kiểu dữ liệu của từng mảng
print(x.dtype, y.dtype, z.dtype)


int64 float64 int64


In [7]:
import numpy as np

x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

# Cộng từng phần tử của 2 mảng
print(x + y)        
print(np.add(x, y))


[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [8]:
import numpy as np

# Trừ từng phần tử của hai mảng
print(x - y)
print(np.subtract(x, y))


[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [9]:
import numpy as np

# Nhân từng phần tử của hai mảng
print(x * y)
print(np.multiply(x, y))


[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [10]:
import numpy as np

# Chia từng phần tử của hai mảng
print(x / y)
print(np.divide(x, y))


[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
